import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "../trpc/client";
import { SessionProvider } from "../providers/session-provider";
import { SearchProvider } from "../modules/home/contexts/search-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <TRPCReactProvider>
          <SessionProvider>
            <SearchProvider>
              {children}
            </SearchProvider>
          </SessionProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
